# Generated by Django 4.2.3 on 2023-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, choices=[('فرانسوی', 'فرانسوی'), ('انگلیسی', 'انگلیسی'), ('آلمانی', 'آلمانی'), ('اسپانیایی', 'اسپانیایی'), ('عربی', 'عربی'), ('روسی', 'روسی')], max_length=30, null=True),
        ),
    ]
