# Generated by Django 4.2.3 on 2023-08-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='کلید')),
                ('value', models.CharField(blank=True, max_length=1000, null=True, verbose_name='مقدار')),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
