# Generated by Django 4.2.3 on 2023-08-22 11:57

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'این شماره موبایل از قبل در سیستم ثبت شده است'}, max_length=110, null=True, unique=True, validators=[user.models.validate_phone]),
        ),
    ]
