# Generated by Django 4.2.3 on 2023-07-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lastname',
        ),
    ]
